services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=db
    volumes:
      - ./mongoData:/data/db
  storage:
    image: redis
    ports:
      - 6379:6379
  delivery:
    image: node:latest
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/delivery
      - REDIS_URL=redis://storage
    depends_on:
      - storage